var prevP=0,nextP=0;function _validateEmail(a){return/^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/.test(a)?!0:!1}function transfert_ami(a,b){postuler(a,b,1)}
function postuler(a,b,c){email=$("#"+b+" #email").val();if($("#"+b).valid()&&0!=$.trim(email).length&&_validateEmail(email))$("#"+a).popup("close"),id_annonce=$("#annonce #"+b+" #id_annonce").val(),a=$("#annonce #"+b+" #subject").val(),b=$("#annonce #"+b+" #message").val(),c?wrp_cpt_mobile("form-envoi-annonce-ami",id_annonce):wrp_cpt_mobile("form-auto-transfert",id_annonce),c?$.jStorage.set("emailami",email):$.jStorage.set("email",email),$.jStorage.reInit(),$.mobile.loading("show"),$.ajax({url:DIRSCRIPTS+
"interface-mobile.php",data:{jsonp:1,put:"candidate-annonce",id:id_annonce,email:email,subject:a,message:b,istransfertami:c},dataType:"jsonp",async:!0,success:function(a){$.mobile.loading("hide");"OK"==a?(setTimeout(function(){$("#waiting_send").popup("close")},200),setTimeout(function(){c?($("#confirm_send_ami").popup({history:!1}),$("#confirm_send_ami").popup("open"),wrp_cpt_mobile("form-envoi-annonce-ami-success",id_annonce)):($("#confirm_send").popup({history:!1}),$("#confirm_send").popup("open"),
wrp_cpt_mobile("form-auto-transfert-success",id_annonce))},300)):(setTimeout(function(){$("#waiting_send").popup("close")},200),setTimeout(function(){$("#error_send").popup({history:!1});$("#error_send").popup("open");c?wrp_cpt_mobile("form-envoi-annonce-ami-error",id_annonce):wrp_cpt_mobile("form-auto-transfert-error",id_annonce)},300))},error:function(){$.mobile.loading("hide");setTimeout(function(){$("#waiting_send").popup("close")},200);setTimeout(function(){$("#error_send").popup({history:!1});
$("#error_send").popup("open");c?wrp_cpt_mobile("form-envoi-annonce-ami-error",id_annonce):wrp_cpt_mobile("form-auto-transfert-error",id_annonce)},300)}});else return setTimeout(function(){$("#waiting_send").popup("close")},200),!1;return!0}
function showAnnonce(a,b){/(?:.*id={1})+(\d+)(.*)/g.exec(a.hash);if(""!=RegExp.$1)var c=RegExp.$1;var e=0;search_list_id?e=search_list_id.length:search_list_id=[];var d=search_list_id.indexOf(c.toString());prevP=0<d?search_list_id[d-1]:null;nextP=d<e-1?search_list_id[d+1]:null;e=a.hash.replace(/\?.*$/,"");d=$(e);$(e).getItem({url:DIRSCRIPTS+"interface-mobile.php",data:{jsonp:1,get:"annonce",id_annonce:c,PREVIOUS:prevP,NEXT:nextP}});b.dataUrl=a.href;$.mobile.changePage(d,b)}
function _refresh_datas(){var a=$.jStorage.get("email");a||(a="");$("#popupPostuler #email").val(a);(a=$.jStorage.get("emailami"))||(a="");$("#popupTransfertAmi #email").val(a)};var DIRHTTP="http://www.batiactuemploi.com/",DIRSCRIPTS="http://bo.v2.batiactuemploi.com/scripts/",pageinit=!1,back_popup_hash="",use_infinite=!0,Tfonctions_search=[],Tregions_search=[],Texperiences_search=[],Tcontrats_search=[],Tregions=[],Tdepts=[],Tfonctions=[],Texperiences=[],Tcontrats=[],Limit_Annonce=200,Limit_Recherche=50,nb_results_by_page=20,current_zonegeo=[],current_fonction=[],current_metier=[],current_experience=[],current_contrat=[],current_motclef="",hash_searh_selected_to_del="",current_nb_annonce=
0,last_search={},search_list_id=[],nb_annonce=2200,nb_annonce_cent_inf=nb_annonce-nb_annonce%100;tsearchs={};var notify=function(a,b,c){var e=$('<p style="display:none;">'+a+"</p>");$(b+" .notifications").each(function(){null==c&&(c=3E3);$(this).append(e);e.slideDown(300,function(){window.setTimeout(function(){e.slideUp(300,function(){e.remove()})},c)})})},remove_notify=function(a){$(a+" .notifications").find("p").remove()};
function pagination(a){var b=Math.ceil(current_nb_annonce/nb_results_by_page);a=Math.floor(a/nb_results_by_page);a<b?($("#recherche #pagin-next").show(),$("#recherche #pagin-next").removeClass("ui-disabled")):($("#recherche #pagin-next").hide(),$("#recherche #pagin-next").addClass("ui-disabled"));1<a?($("#recherche #pagin-prev").show(),$("#recherche #pagin-prev").removeClass("ui-disabled")):($("#recherche #pagin-prev").hide(),$("#recherche #pagin-prev").addClass("ui-disabled"));$("#recherche #pagin-pages").html(a+
"/"+b);$("#recherche .ui-select").css("display","none");$("#recherche #select-page").html("");$("#recherche #select-page").append('<option value="0">Aller \u00e0 la page</option>');for(i=1;i<=b;i++)i!=a&&$("#recherche #select-page").append('<option value="'+i+'">page '+i+"</option>");1<b&&($("#recherche #select-page").selectmenu("refresh",!0),$("#recherche .ui-select").css("display","inline"),$("#recherche #pagin-pages").css("display","inline"))}
function uncheck_cac(a,b){window["current_"+a]=[];$(".check"+a).each(function(){this.id!=b.attr("id")&&$(this).prop("checked",!1);$(this).checkboxradio().checkboxradio("refresh")});b.prop("checked")&&window["current_"+a].push(b.attr("value"))}function view_list_mes_recherches(){$("#resultat-mes-recherches").completeListMesRecherches({})}
function reset_search(a){current_zonegeo=[];current_fonction=[];current_metier=[];current_experience=[];current_contrat=[];current_motclef="";current_nb_annonce=0;$("[id^=selected-detail-page-]").text("");$("[id=recherche-detail-mot-clef]").val("");$(".check_cac").each(function(){$(this).prop("checked",!1);$(this).checkboxradio().checkboxradio("refresh")});a&&$.mobile.changePage("#recherche-detail")}
function saved_last_search(){criteres_last_search={};criteres_last_search.current_zonegeo=current_zonegeo;criteres_last_search.current_fonction=current_fonction;criteres_last_search.current_experience=current_experience;criteres_last_search.current_contrat=current_contrat;criteres_last_search.current_motclef=current_motclef;$.jStorage.set("last_search",criteres_last_search)}
function saved_search(){(tsearchs=$.jStorage.get("tsearchs"))||(tsearchs={});var a={};a.current_zonegeo=current_zonegeo;a.current_fonction=current_fonction;a.current_experience=current_experience;a.current_contrat=current_contrat;a.current_motclef=current_motclef;var b=convert_array_to_hash(a);tsearchs.hasOwnProperty(b)?$("#popupAlreadyExistsSaveSearch").popup("open"):(tsearchs[b]=a,$.jStorage.set("tsearchs",tsearchs),$("#popupSaveSearch").popup("open"))}
function convert_array_to_hash(a){var b=[];$.each(a,function(a,e){b.push(a+":"+e)});return b.join(", ").hashCode()}String.prototype.hashCode=function(){var a=0,b,c;nb=this.length;if(0==nb)return a;b=0;for(l=nb;b<l;b++)c=this.charCodeAt(b),a=(a<<5)-a+c,a|=0;return a};function gotosearch(a){load_searh_from_hash(a)?go_url_recherche():alert("erreur");return!1}
function select_del_search_from_hash(a){hash_search_selected_to_del=a;$("#confirmDeleteSearch").popup();$("#confirmDeleteSearch").popup("open",{history:!1})}function candel_del_search(){hash_search_selected_to_del=""}
function del_searh_from_hash(a){(tsearchs=$.jStorage.get("tsearchs"))||(tsearchs={});if(tsearchs.hasOwnProperty(a))return notify("Suppression...","#mes-recherches"),delete tsearchs[a],$.jStorage.set("tsearchs",tsearchs),$("#mes-recherches #resultat-mesrecherches").hide(),view_list_mes_recherches(),$("#mes-recherches #resultat-mesrecherches").show(),$("#mes-recherches").trigger("create"),!0;notify("Erreur, ce hash ne correspond pas!","#mes-recherches");return!1}
function load_searh_from_hash(a){(tsearchs=$.jStorage.get("tsearchs"))||(tsearchs={});if(tsearchs.hasOwnProperty(a))notify("Rechargement","#mes-recherches");else return notify("Erreur, ce hash ne correspond pas!","#mes-recherches"),!1;reset_search();criteres_search_current_hash=tsearchs[a];$.each(criteres_search_current_hash,function(a,c){window[a]=c});set_fields_from_current();return!0}
function set_fields_from_current(){$("[id^=selected-detail-page-]").html("");$.each(current_zonegeo,function(a){value=current_zonegeo[a];$("[cac_type=zonegeo][value="+value+"]").attr("id");$("[cac_type=zonegeo][value="+value+"]").prop("checked",!0);$("[cac_type=zonegeo][value="+value+"]").checkboxradio().checkboxradio("refresh");a=get_value_by_key(Tregions,value);$("#selected-detail-page-zonegeo").html(a)});$.each(current_fonction,function(a){value=current_fonction[a];$("[cac_type=fonction][value="+
value+"]").attr("id");$("[cac_type=fonction][value="+value+"]").prop("checked",!0);$("[cac_type=fonction][value="+value+"]").checkboxradio().checkboxradio("refresh");a=get_value_by_key(Tfonctions,value);$("#selected-detail-page-fonction").html(a)});$.each(current_contrat,function(a){value=current_contrat[a];$("[cac_type=contrat][value="+value+"]").attr("id");$("[cac_type=contrat][value="+value+"]").prop("checked",!0);$("[cac_type=contrat][value="+value+"]").checkboxradio().checkboxradio("refresh");
a=get_value_by_key(Tcontrats,value);$("#selected-detail-page-contrat").html(a)});$.each(current_experience,function(a){value=current_experience[a];$("[cac_type=experience][value="+value+"]").attr("id");$("[cac_type=experience][value="+value+"]").prop("checked",!0);$("[cac_type=experience][value="+value+"]").checkboxradio().checkboxradio("refresh");a=get_value_by_key(Texperiences,value);$("#selected-detail-page-experience").html(a)});$("#recherche-detail-mot-clef").val(current_motclef)}
function get_current_search_wreport(a){if("undefined"==typeof a||null==a||void 0==a)a=0;var b="",c,e="zonegeo";c=""+(e+" : "+current_zonegeo.join(",")+"\t");var b=b+(e+" : "),d=0;$.each(current_zonegeo,function(a){value=current_zonegeo[a];0<d&&(b+=",");b+=get_value_by_key(Tregions,value);d++});b+="\t";e="fonction";c+=e+" : "+current_fonction.join(",")+"\t";b+=e+" : ";d=0;$.each(current_fonction,function(a){value=current_fonction[a];0<d&&(b+=",");b+=get_value_by_key(Tfonctions,value);d++});b+="\t";
e="contrat";c+=e+" : "+current_contrat.join(",")+"\t";b+=e+" : ";d=0;$.each(current_contrat,function(a){value=current_contrat[a];0<d&&(b+=",");b+=get_value_by_key(Tcontrats,value);d++});b+="\t";e="experience";c+=e+" : "+current_experience.join(",")+"\t";b+=e+" : ";d=0;$.each(current_experience,function(a){value=current_experience[a];0<d&&(b+=",");b+=get_value_by_key(Texperiences,value);d++});b+="\t";e="motclef";c+=e+" : "+current_motclef+"\t";b+=e+" : "+current_motclef+"\t";return a?b:c}
function get_value_by_key(a,b){return void 0===a[b]?"":a[b]}function load_last_searh(){reset_search(!0);criteres_last_search=$.jStorage.get("last_search");$.each(criteres_last_search,function(a,b){window[a]=b});set_fields_from_current()}
function init_global(){$.ajax({url:DIRSCRIPTS+"interface-mobile.php",data:{jsonp:1,get:"zone-geo"},dataType:"jsonp",async:!1,cache:!1}).done(function(a){Tregions_search=[];var b=0;for(code in a)label=a[code],Tregions_search.push({item_value:code,item_label:label,item_index:b,type:"zonegeo"}),Tregions[code]=label,b++});$.ajax({url:DIRSCRIPTS+"interface-mobile.php",data:{jsonp:1,get:"nb_annonce"},dataType:"jsonp",async:!1,cache:!1,success:function(a){nb_annonce=a.nb;nb_annonce_cent_inf=nb_annonce-nb_annonce%
100;$("#nbannonce_cent_inf").text(nb_annonce_cent_inf)},error:function(a){}});$.ajax({url:DIRSCRIPTS+"interface-mobile.php",data:{jsonp:1,get:"fonction"},dataType:"jsonp",async:!1,cache:!1}).done(function(a){Tfonctions_search=[];Tfonctions=[];var b=0;for(item in a)for(fonction in a[item].fonction)label=a[item].fonction[fonction],Tfonctions_search.push({item_value:fonction,item_label:label,item_index:b,type:"fonction"}),Tfonctions[fonction]=label,b++});$.ajax({url:DIRSCRIPTS+"interface-mobile.php",
data:{jsonp:1,get:"dept"},dataType:"jsonp",async:!1,cache:!1}).done(function(a){Tdepts=[];var b=0;for(code in a)label=a[code],Tdepts[code]=label,b++});load_contrats();load_experiences();initSearch();return!0}function initSearch(){(tsearchs=$.jStorage.get("tsearchs"))||(tsearchs={});search_list_id=[];criteres_last_search=$.jStorage.get("last_search")}
function load_contrats(){$.ajax({url:DIRSCRIPTS+"interface-mobile.php",data:{jsonp:1,get:"contrat"},dataType:"jsonp",async:!1,cache:!1}).done(function(a){var b=Handlebars.compile($("#recherche-detail-tpl").html());Tcontrats_search=[];Tcontrats=[];var c=0;for(code in a)label=a[code],Tcontrats_search.push({item_value:code,item_label:label,item_index:c,type:"contrat"}),Tcontrats[code]=label,c++;$("#recherche-detail-contrat").html(b(Tcontrats_search))})}
function load_experiences(){$.ajax({url:DIRSCRIPTS+"interface-mobile.php",data:{jsonp:1,get:"experience"},dataType:"jsonp",async:!1,cache:!1}).done(function(a){var b=Handlebars.compile($("#recherche-detail-tpl").html());Texperiences_search=[];Texperiences=[];var c=0;for(code in a)label=a[code],Texperiences_search.push({item_value:code,item_label:label,item_index:c,type:"experience"}),Texperiences[code]=label,c++;$("#recherche-detail-experience").html(b(Texperiences_search))})}
function launchSearch(a,b){search_list_id=[];null==a&&(a=!1);var c=$("#recherche-detail-mot-clef").val(),e="",d="";a?($.each(current_zonegeo,function(a){""!=d&&(d+="|");d+=this}),$.each(current_fonction,function(a){""!=e&&(e+="|");e+=this})):d=$("#accueil #zone-geo").val();current_motclef=$("[id=recherche-detail-mot-clef]").val();if(b)var f=(b-1)*nb_results_by_page,g=f+nb_results_by_page;else f=parseInt($("#recherche #next").attr("data-next")),g=f+nb_results_by_page;f>Limit_Annonce?($("#recherche #next").attr("data-next",
f),g=Limit_Annonce):f>current_nb_annonce?($("#recherche #next").attr("data-next",f),g=current_nb_annonce):$("#recherche #next").attr("data-next",g);f=$("#recherche").children(":jqmData(role=content)");f.find("#nb_results").html("<br />");f.find("#pagin-prev").css("display","none");f.find("#pagin-next").css("display","none");f.find("#pagin-pages").css("display","none");$("#select-page").parents(".ui-select").css("display","none");f.find(".btn_display1").css("display","none");f.find(".btn_display2").css("display",
"none");$("#resultat-recherche").completeListItem({url:DIRSCRIPTS+"interface-mobile.php",data:{get:"search",jsonp:1,mot:c,zonegeo:d,fonction:e,metier:"",experience:"",contrat:"",length:g}});use_infinite&&$("#resultat-recherche").show();saved_last_search();return!1}function execute_search(a,b){var c=a.hash.replace(/\?.*$/,""),c=$(c);use_infinite||launchSearch(1,1);c.page();b.dataUrl=a.href;$.mobile.changePage(c,b);null==b.noLoading&&$.mobile.loading("show")}

function check_params(){save_current_criteres();go_url_recherche()}

function go_url_recherche(){var a=$("#recherche").children(":jqmData(role=content)");a.find("#resultat-recherche").html("");a.find("#nb_results").html("<br />");a.find("#pagin-prev").css("display","none");a.find("#pagin-next").css("display","none");a.find("#pagin-pages").css("display","none");$("#select-page").parents(".ui-select").css("display","none");a.find(".btn_display1").css("display","none");a.find(".btn_display2").css("display","none");$("#recherche #next").addClass("displaynone");newurl=
"#recherche?zone="+current_zonegeo.join("-")+"&fct="+current_experience.join("-")+current_contrat.join("-")+current_fonction.join("-")+"&motclef="+current_motclef;$.mobile.changePage(newurl);return!0}
function save_current_criteres(){0<$(".checkzonegeo").lenght&&(current_zonegeo=[],$(".checkzonegeo").each(function(a){$(this).prop("checked")&&current_zonegeo.push($(this).val())}));0<$(".checkfonction").lenght&&(current_fonction=[],$(".checkfonction").each(function(a){$(this).prop("checked")&&current_fonction.push($(this).val())}));0<$(".checkcontrat").lenght&&(current_contrat=[],$(".checkcontrat").each(function(a){$(this).prop("checked")&&current_contrat.push($(this).val())}));0<$(".checkexperience").lenght&&
(current_experience=[],$(".checkexperience").each(function(a){$(this).prop("checked")&&current_experience.push($(this).val())}));current_motclef=$("[id=recherche-detail-mot-clef]").val();return!1};(function(a){a.fn.extend({completeListMesRecherches:function(b){b=a.extend({template:"#mes-recherches-resultat-tpl",url:"fill-url-source",data:{}},b);var c=a(this),e=Handlebars.compile(a(b.template).html());null==b.noLoading&&a.mobile.loading("show");nb=Object.keys(tsearchs).length;c.html("");var d=[];a.each(tsearchs,function(a,b){var c=[];c.item_no_criteres="Recherche globale (sans crit\u00e8re)";for(k in b){""!=b[k]&&(c.item_no_criteres=null);switch(k){case "current_zonegeo":c["item_lib_"+k]=""==
b[k]?b[k]:Tregions[b[k]];break;case "current_fonction":c["item_lib_"+k]=""==b[k]?b[k]:Tfonctions[b[k]];break;case "current_experience":c["item_lib_"+k]=""==b[k]?b[k]:Texperiences[b[k]];break;case "current_contrat":c["item_lib_"+k]=""==b[k]?b[k]:Tcontrats[b[k]]}c["item_"+k]=b[k]}c.item_hash=a;d.push(c)});c.html(e(d));c.show();null==b.noLoading&&(remove_notify("#mes-recherches"),a.mobile.loading("hide"));use_infinite&&(a.waypoints(),a.waypoints("refresh"))},completeListItem:function(b){b=a.extend({template:"#recherche-resultat-tpl",
url:"fill-url-source",data:{}},b);var c=a(this),e=Handlebars.compile(a(b.template).html());null==b.noLoading&&a.mobile.loading("show");null==b.dataType&&(b.dataType="jsonp");a.ajax({url:b.url,data:b.data,dataType:b.dataType,async:!1}).done(function(d){data=d.TResults;nbTotal=d.nb;var f=[];"xml"==b.dataType?(xml=data,data=[],a("item",xml).each(function(b){b=blank.clone();b.removeAttr("id");ligne=b.html();a("*",this).each(function(b,c){k=c.tagName;v=a(c).text();"enclosure"==k&&(v=a(c).attr("url"),k=
"image");ligne=ligne.replace(RegExp("item_"+k+"","gi"),v)});b.html(ligne);b.show();c.append(b)})):(nb=data.length,a.each(data,function(a,b){var c=0<a?data[a-1].origine:null,e=a<nb-1?data[a+1].origine:null,d=[];search_list_id.push(data[a].origine.toString());for(k in b){switch(k){case "region":d["item_lib_"+k]="";var g=b[k]+"",g=g.split(",");for(j in g)""!=d["item_lib_"+k]&&(d["item_lib_"+k]+=","),d["item_lib_"+k]+=Tregions[g[j]];break;case "dept":d["item_lib_"+k]="";g=b[k]+"";g=g.split(",");for(j in g)""!=
d["item_lib_"+k]&&(d["item_lib_"+k]+=","),d["item_lib_"+k]+=Tdepts[g[j]];break;case "contrat":""==b[k]&&(b[k]="Tous contrats")}d["item_"+k]=b[k]}d.item_previous=c;d.item_next=e;f.push(d)}));current_nb_annonce=nbTotal;if(!use_infinite){var g=parseInt(a("#recherche #next").attr("data-next"));d=g-nb_results_by_page-1;0>d&&(d=0);f=f.slice(d,g-1)}c.html(e(f));d=a("#recherche").children(":jqmData(role=content)");d.find("#nb_results").removeClass("noresult");switch(nbTotal){case 0:res="Aucune offre d'emploi ne correspond \u00e0 vos crit\u00e8res";
d.find("#nb_results").addClass("noresult");break;case 1:res="1 offre d'emploi";break;case Limit_Annonce:res=nbTotal+" premi\u00e8res offres d'emploi";break;default:res=nbTotal+" offres d'emploi"}c.show();c.listview().listview("refresh");d.find("#nb_results").text(res);d.find(".btn_display1").css("display","block");nbTotal>nb_results_by_page&&d.find(".btn_display2").css("display","block");use_infinite&&(a("#recherche #next").trigger("create"),a("#recherche #next").button(),current+nb_results_by_page<=
current_nb_annonce?a("#recherche #next").removeClass("displaynone"):a("#recherche #next").addClass("displaynone"),a("#recherche #next").trigger("create"));null==b.noLoading&&(remove_notify("#recherche"),a.mobile.loading("hide"));use_infinite?(a.waypoints(),a.waypoints("refresh")):(pagination(g),a.mobile.silentScroll(0))})},getItem:function(b){b=a.extend({template:"#annonce-detail-tpl",itemtarget:"#annonce",url:"fill-url-source",data:{}},b);a(this).attr("id");var c=Handlebars.compile(a(b.template).html());
a.mobile.loading("show");a.ajax({url:b.url,data:b.data,dataType:"jsonp",async:!1,success:function(e){a(b.itemtarget+" :jqmData(role=footer)").remove();a(b.itemtarget+' :jqmData(class="content_annonce")').remove();a(b.itemtarget).append(c(e));_refresh_datas();e=Handlebars.compile(a("#nav-annonce-detail-tpl").html());Tab=[];Tab.nav=[{PREVIOUS:prevP,NEXT:nextP}];TabComplete=[];TabComplete.push(Tab);a("#annonce #nav-annonce").remove();a("#annonce").append(e(TabComplete)).trigger("pagecreate");a("#annonce").trigger("create");
a.mobile.loading("hide")},error:function(){a.mobile.loading("hide")}});return this}})})(jQuery);var _NB_MAX_CONTENU_=1,_TAILLE_MAX_CONTENU_=100,_TAILLE_MAX_CHAINE_=50,_TAILLE_MAX_ALPHANUM_=30,WEBO_ID_GROUPE=284488,COOKIE_SEGMENTATION="wbo_segment_";
function wreport_counter(a,b,c,e,d,f,g){this.site=c;this.section;this.subsection;this.content=this.channel="";this.nb_content=0;this.url="";this.frame=e;this.segmentation=["","","","",""];this.profiles="";this.profiling_cookie_mode=1;this.cookie_segmentation=COOKIE_SEGMENTATION;this.domaine_segmentation="";this.counter=new Image(1,1);this.profiling_cookie_mode=profiling_cookie_mode;this.generate_url=generate_url;this.add_content=add_content;this.add_channel=add_channel;this.add_group=add_group;this.add_profile=
add_profile;this.add_profiles=add_profiles;this.delete_profiles=delete_profiles;this.get_profiles=get_profiles;this.count=count;this.section=traite_chaine(a,_TAILLE_MAX_ALPHANUM_);this.subsection=traite_chaine(b,_TAILLE_MAX_ALPHANUM_);null!=d&&this.add_channel(d);null!=f&&null!=g&&this.add_group(f,g);this.cookie_segmentation+=c}
function generate_url(){var a=new Date;this.date=parseInt(a.getTime()/1E3-60*a.getTimezoneOffset());this.ref=""+escape(document.referrer);this.ta="0x0";this.co=0;this.nav=navigator.appName;this.get_profiles();4<=parseInt(navigator.appVersion)&&(this.ta=screen.width+"x"+screen.height,this.co="Netscape"!=this.nav?screen.colorDepth:screen.pixelDepth);if(null!=this.frame&&"Netscape"!=this.nav){a="parent.document.referrer";if(5>this.frame&&0<this.frame)for(_k=this.frame;1<_k;_k--)a="parent."+a;a=eval(a);
if(document.referrer==parent.location||""==document.referrer)this.ref=""+escape(a)}this.url="https:"==location.protocol?"https://capinfoprogroupe.solution.weborama.fr":"http://capinfoprogroupe.solution.weborama.fr";this.url+="/fcgi-bin/comptage_wreport.fcgi?WRP_ID="+this.site;null!=this.profiles&&(this.url+="&WRP_PFL="+this.profiles);var a=-1!=wf_uaO("mac"),b=-1!=wf_uaO("opera");a||b||(a=navigator.userAgent.indexOf("MSIE"),0<a&&5<=parseInt(navigator.userAgent.charAt(a+5))&&(document.body.addBehavior("#default#clientCaps"),
this.cnx="modem"==document.body.connectionType?"A":"B",document.body.addBehavior("#default#homePage"),this.home=document.body.isHomePage(location.href)?"A":"B",this.url+="&CONN="+this.cnx+"&ISHOME="+this.home));this.url+="&WRP_SECTION="+this.section+"&WRP_SUBSECTION="+this.subsection;null!=this.site_grp&&(null!=this.section_grp&&null!=this.subsection_grp)&&(this.url+="&WRP_ID_GRP="+this.site_grp+"&WRP_SECTION_GRP="+this.section_grp+"&WRP_SUBSECTION_GRP="+this.subsection_grp);null!=this.content&&(this.url+=
"&WRP_CONTENT="+this.content);null!=this.channel&&(this.url+="&WRP_CHANNEL="+this.channel);this.url+="&ver=2&da2="+this.date+"&ta="+this.ta+"&co="+this.co+"&ref="+this.ref}function count(){this.generate_url();this.counter.src=this.url;return 1}function add_channel(a){if(null==a||""==a)return 0;this.channel=traite_chaine(a,_TAILLE_MAX_CHAINE_);return 1}
function add_group(a,b){this.site_grp=WEBO_ID_GROUPE;this.section_grp=traite_chaine(a,_TAILLE_MAX_ALPHANUM_);this.subsection_grp=traite_chaine(b,_TAILLE_MAX_ALPHANUM_)}function add_content(a){if(null==a||""==a)return 0;this.nb_content++;if(this.nb_content>_NB_MAX_CONTENU_)return 0;1<this.nb_content&&(this.content=this.content.concat("|"));a=a.replace("|"," ");this.content=this.content.concat(traite_chaine(a,_TAILLE_MAX_CONTENU_));return 1}
function profiling_cookie_mode(a){this.profiling_cookie_mode="on"==a?1:0}
function add_profile(a,b){a=parseInt(a,10);if(1>a||5<a)return-2;if(0==this.profiling_cookie_mode)return a--,this.segmentation[a]=b,1;if(3>=parseInt(navigator.appVersion,10))return-1;nb_mois=12;/^\d+$/.test(b)&&(b=encode_en_lettre(b));if(/^\w*$/.test(b)){var c=GetCookie(this.cookie_segmentation);tab_segment=["","","","",""];if(null!=c&&(tab_segment=c.split("|"),5!=tab_segment.length&&(tab_segment=("","","","","")),tab_segment[a-1]==b))return 1;""==this.domaine_segmentation&&(this.domaine_segmentation=
window.location.host,tab_points=[],tab_points=window.location.host.split("."),2<tab_points.length&&(this.domaine_segmentation=this.domaine_segmentation.substring(this.domaine_segmentation.indexOf("."),this.domaine_segmentation.length)),2==tab_points.length&&(this.domaine_segmentation="."+this.domaine_segmentation));for(var c="",e=1;5>=e;e++){e==a&&(tab_segment[e-1]=b);if(""==tab_segment[e-1]||null==tab_segment[e-1])tab_segment[e-1]="";c+=tab_segment[e-1];5>e&&(c+="|")}expd=new Date;expd.setTime(expd.getTime()+
2592E6*nb_mois);SetCookie(this.cookie_segmentation,c,expd,"/",this.domaine_segmentation);return 2}return-3}function add_profiles(a,b,c,e,d){this.add_profile(1,a);this.add_profile(2,b);this.add_profile(3,c);this.add_profile(4,e);this.add_profile(5,d)}function delete_profiles(){0==this.profiling_cookie_mode?this.segmentation=["","","","",""]:(expd=new Date,expd.setTime(expd.getTime()-864E5),SetCookie(this.cookie_segmentation,"||||",expd,"/",this.domaine_segmentation))}
function get_profiles(){this.profiles=GetCookie(this.cookie_segmentation);if(null==this.profiles){this.profiles="";for(var a=/^\d+$/,b=1;5>=b;b++)a.test(this.segmentation[b-1])&&(this.segmentation[b-1]=encode_en_lettre(this.segmentation[b-1])),this.profiles+=this.segmentation[b-1],5>b&&(this.profiles+="|")}this.profiles=escape(this.profiles)}
function encode_en_lettre(a){a=parseInt(a,10);if(2500<a)return"";var b=parseInt(a/52,10),b=b+65;90<b&&(b+=6);a=a%52+65;90<a&&(a+=6);return String.fromCharCode(b)+String.fromCharCode(a)}function traite_chaine(a,b){var c=traduction(a),e,d="";if(null==c)return"";c=(""+c).substr(0,b);for(e=0;e<c.length;e++){var f=c.charAt(e);-1!="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-.,;:_ ".indexOf(f)&&(d+=f)}d=unicite_espace(d);return d=escape(d)}
function convertir(a){a=a.replace(/&#(\d+);/,"$1");return String.fromCharCode(a)}function traduction(a){for(var b=unescape(a),c=0;b!=a&&5>c;)c++,a=b,b=unescape(b);return b.replace(/&#(\d+);/gi,convertir)}function unicite_espace(a){a=a.replace(/(\s+)/g," ");return a=a.replace(/(^\s*)|(\s*$)/g,"")}function wf_uaO(a){return navigator.userAgent.toLowerCase().indexOf(a)}
function getCookieVal(a){var b=document.cookie.indexOf(";",a);-1==b&&(b=document.cookie.length);return unescape(document.cookie.substring(a,b))}function GetCookie(a){a+="=";for(var b=a.length,c=document.cookie.length,e=0;e<c;){var d=e+b;if(document.cookie.substring(e,d)==a)return getCookieVal(d);e=document.cookie.indexOf(" ",e)+1;if(0==e)break}return null}
function SetCookie(a,b,c,e,d,f){document.cookie=a+"="+escape(b)+(c?"; expires="+c.toGMTString():"")+(e?"; path="+e:"")+(d?"; domain="+d:"")+(f?"; secure":"")}function wreport(a,b,c,e,d,f){a=new wreport_counter(a,b,c,e,f);a.add_content(d);a.count()}function wreport_groupe(a,b,c,e,d,f,g,h){a=new wreport_counter(a,b,c,f,h,e,d);a.add_content(g);a.count()}function wreport_click(a,b,c,e,d,f,g){b=new wreport_counter(b,c,e,d,g);b.add_content(f);b.count();b.counter.onload=function(){document.location=a}}
function wreport_click_groupe(a,b,c,e,d,f,g,h,m){b=new wreport_counter(b,c,e,g,m,d,f);b.add_content(h);b.count();b.counter.onload=function(){document.location=a}}wreport_ok=1;
